version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - localdb:/var/lib/mysql

volumes:
  localdb:
  
# Docker run command - docker run -d --rm -e MYSQL_DATABASE='db' -e MYSQL_USER='user' -e MYSQL_PASSWORD='pass' -e MYSQL_ROOT_PASSWORD='rootpass' -p 3306:3306 --name mysql_local mysql
